services:
  f1-racer-ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: f1-racer-ai-agent
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - NLTK_DATA=/home/f1agent/nltk_data
      - DOCKER_CONTAINER=true
    env_file:
      - .env
    volumes:
      # Optional: Mount logs directory for persistence
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/agent/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s